f=open("/Users/vector/Desktop/Vector/B2-V25HFS1/PYTHON/exam-ques/exam-10/data.txt","r")
s=f.read()
f.close()
f=open("/Users/vector/Desktop/Vector/B2-V25HFS1/PYTHON/exam-ques/exam-10/data.txt","w")
f.write(s[::-1])
f.close()
